import { MigrationInterface, QueryRunner } from "typeorm";

export class InitFreshSchema1755458611706 implements MigrationInterface {
    name = 'InitFreshSchema1755458611706'

    public async up(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`CREATE TABLE "property" ("id" SERIAL NOT NULL, "portfolio_id" integer NOT NULL, "name" character varying NOT NULL, "address_line1" character varying NOT NULL, "address_line2" character varying, "city" character varying NOT NULL, "state" character varying NOT NULL, "postal_code" character varying NOT NULL, "country" character varying NOT NULL, "latitude" numeric(10,6) NOT NULL, "longitude" numeric(10,6) NOT NULL, "property_type" character varying NOT NULL, "description" text, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_d80743e6191258a5003d5843b4f" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_85d8ae8f941ec5241e515bf69c" ON "property" ("property_type") `);
        await queryRunner.query(`CREATE INDEX "IDX_45cbf848b958b21e6c1547df95" ON "property" ("city", "state") `);
        await queryRunner.query(`CREATE TABLE "portfolio" ("id" SERIAL NOT NULL, "name" character varying NOT NULL, "landlord_id" integer NOT NULL, "subscription_plan" character varying NOT NULL, "status" character varying NOT NULL, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_6936bb92ca4b7cda0ff28794e48" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_93a62ca3d718772835184d0dda" ON "portfolio" ("status") `);
        await queryRunner.query(`CREATE INDEX "IDX_ab77879067dc815468de31e63c" ON "portfolio" ("landlord_id") `);
        await queryRunner.query(`CREATE TABLE "notification" ("id" SERIAL NOT NULL, "portfolio_id" integer NOT NULL, "user_id" integer, "type" character varying NOT NULL, "message" text NOT NULL, "subject_type" character varying, "subject_id" bigint, "is_read" boolean NOT NULL DEFAULT false, "channel" character varying NOT NULL, "sent_at" TIMESTAMP, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_705b6c7cdf9b2c2ff7ac7872cb7" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_5ec9aa64430984435e8a026266" ON "notification" ("portfolio_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_7d60478bf7cacbbe3f7ae1bc1c" ON "notification" ("sent_at") `);
        await queryRunner.query(`CREATE INDEX "IDX_aedc307c7e60ecb138e3f90ff8" ON "notification" ("is_read") `);
        await queryRunner.query(`CREATE INDEX "IDX_928b7aa1754e08e1ed7052cb9d" ON "notification" ("user_id") `);
        await queryRunner.query(`CREATE TABLE "user" ("id" SERIAL NOT NULL, "name" character varying NOT NULL, "email" character varying NOT NULL, "phone" character varying, "password_hash" character varying NOT NULL, "role" character varying NOT NULL, "profile_image_url" character varying, "is_active" boolean NOT NULL DEFAULT true, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "UQ_e12875dfb3b1d92d7d7c5377e22" UNIQUE ("email"), CONSTRAINT "PK_cace4a159ff9f2512dd42373760" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_e12875dfb3b1d92d7d7c5377e2" ON "user" ("email") `);
        await queryRunner.query(`CREATE TABLE "portfolio_member" ("id" SERIAL NOT NULL, "portfolio_id" integer NOT NULL, "user_id" integer NOT NULL, "role" character varying NOT NULL, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "UQ_c3f978c50b74de4cd6587b36084" UNIQUE ("portfolio_id", "user_id"), CONSTRAINT "PK_0bc1504f157abeb106a54c517a2" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_a2db3bb0a70771c7027c7309bf" ON "portfolio_member" ("user_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_c02eecc90e0de3c1742116fefa" ON "portfolio_member" ("portfolio_id") `);
        await queryRunner.query(`CREATE TABLE "unit" ("id" SERIAL NOT NULL, "portfolio_id" integer NOT NULL, "property_id" integer NOT NULL, "label" character varying NOT NULL, "bedrooms" integer, "bathrooms" numeric(3,1), "sqft" integer, "market_rent" numeric(12,2), "status" character varying NOT NULL DEFAULT 'vacant', "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "UQ_9c25f08c1686493fe5e5d03f325" UNIQUE ("portfolio_id", "property_id", "label"), CONSTRAINT "PK_4252c4be609041e559f0c80f58a" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_ffd1df4d8c19a8bd49fcd8af71" ON "unit" ("property_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_de310cad4b93a905a01236c9ef" ON "unit" ("portfolio_id") `);
        await queryRunner.query(`CREATE TABLE "tenant" ("id" SERIAL NOT NULL, "portfolio_id" integer NOT NULL, "first_name" character varying NOT NULL, "last_name" character varying NOT NULL, "email" character varying, "phone" character varying, "is_active" boolean NOT NULL DEFAULT true, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_da8c6efd67bb301e810e56ac139" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_3ce58fb50f708bf5666525d901" ON "tenant" ("portfolio_id") `);
        await queryRunner.query(`CREATE TABLE "lease" ("id" SERIAL NOT NULL, "portfolio_id" integer NOT NULL, "unit_id" integer NOT NULL, "start_date" date NOT NULL, "end_date" date NOT NULL, "rent" numeric(12,2) NOT NULL, "deposit" numeric(12,2) NOT NULL DEFAULT '0', "status" character varying NOT NULL DEFAULT 'draft', "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_954811694773f24986695203663" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_ca091675febe801029d4db0f64" ON "lease" ("unit_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_007935258e588d12f311001000" ON "lease" ("portfolio_id") `);
        await queryRunner.query(`CREATE TABLE "lease_tenant" ("lease_id" integer NOT NULL, "tenant_id" integer NOT NULL, CONSTRAINT "PK_b5f56ce129b079a8b45f3250081" PRIMARY KEY ("lease_id", "tenant_id"))`);
        await queryRunner.query(`CREATE TABLE "lease_charge" ("id" SERIAL NOT NULL, "portfolio_id" integer NOT NULL, "lease_id" integer NOT NULL, "name" character varying NOT NULL, "amount" numeric(12,2) NOT NULL, "cadence" character varying NOT NULL DEFAULT 'monthly', "start_date" date NOT NULL, "end_date" date, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_09772a7297c9b7a7e1300be76ba" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_4ecd198da30e9be7ae2c8ffe9d" ON "lease_charge" ("lease_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_5e94d7688d7fbee5a84b22fd37" ON "lease_charge" ("portfolio_id") `);
        await queryRunner.query(`CREATE TABLE "invoice_item" ("id" SERIAL NOT NULL, "invoice_id" integer NOT NULL, "name" character varying NOT NULL, "qty" numeric(10,2) NOT NULL DEFAULT '1', "unit_price" numeric(12,2) NOT NULL, "amount" numeric(12,2) NOT NULL, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_621317346abdf61295516f3cb76" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_9830c1881dd701d440c2164c3c" ON "invoice_item" ("invoice_id") `);
        await queryRunner.query(`CREATE TABLE "invoice" ("id" SERIAL NOT NULL, "portfolio_id" integer NOT NULL, "lease_id" integer, "issue_date" date NOT NULL, "due_date" date NOT NULL, "status" character varying NOT NULL DEFAULT 'open', "subtotal" numeric(12,2) NOT NULL, "tax" numeric(12,2) NOT NULL DEFAULT '0', "total" numeric(12,2) NOT NULL, "balance" numeric(12,2) NOT NULL, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_15d25c200d9bcd8a33f698daf18" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_fc80c537671ddc29aab503e8fd" ON "invoice" ("due_date") `);
        await queryRunner.query(`CREATE INDEX "IDX_978738e43651936fd1b60c7e84" ON "invoice" ("lease_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_e423299afbc7c08bac6857a177" ON "invoice" ("portfolio_id") `);
        await queryRunner.query(`CREATE TABLE "payment" ("id" SERIAL NOT NULL, "portfolio_id" integer NOT NULL, "invoice_id" integer, "received_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "method" character varying, "amount" numeric(12,2) NOT NULL, "reference" character varying, "status" character varying NOT NULL DEFAULT 'succeeded', "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_fcaec7df5adf9cac408c686b2ab" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_2c5c19ef08665dd1d123aebe50" ON "payment" ("received_at") `);
        await queryRunner.query(`CREATE INDEX "IDX_20cc84d8a2274ae86f551360c1" ON "payment" ("invoice_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_e03401e14c266f0f4e68954bf6" ON "payment" ("portfolio_id") `);
        await queryRunner.query(`CREATE TABLE "maintenance_request" ("id" SERIAL NOT NULL, "portfolio_id" integer NOT NULL, "property_id" integer NOT NULL, "unit_id" integer, "tenant_id" integer, "title" character varying NOT NULL, "description" text, "priority" character varying NOT NULL DEFAULT 'medium', "status" character varying NOT NULL DEFAULT 'open', "requested_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "completed_at" TIMESTAMP WITH TIME ZONE, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_d12252413b60c63b57fc4c0d0c9" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_c4eaf0a99dece1b96c9a30185b" ON "maintenance_request" ("status") `);
        await queryRunner.query(`CREATE INDEX "IDX_b36c96f0315a7ffd46d07e3a93" ON "maintenance_request" ("portfolio_id") `);
        await queryRunner.query(`CREATE TABLE "work_order" ("id" SERIAL NOT NULL, "portfolio_id" integer NOT NULL, "request_id" integer NOT NULL, "vendor_id" bigint, "scheduled_for" TIMESTAMP WITH TIME ZONE, "cost_estimate" numeric(12,2), "cost_actual" numeric(12,2), "status" character varying NOT NULL DEFAULT 'scheduled', "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_0730e63dd523d397530859cb6d1" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_8e6b62c4caa787023767ae736b" ON "work_order" ("portfolio_id") `);
        await queryRunner.query(`CREATE TABLE "document" ("id" SERIAL NOT NULL, "portfolio_id" integer NOT NULL, "subject_type" character varying NOT NULL, "subject_id" bigint NOT NULL, "filename" character varying NOT NULL, "storage_key" character varying NOT NULL, "mime_type" character varying, "size_bytes" bigint, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_e57d3357f83f3cdc0acffc3d777" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_e56984b82e77d9ec67652cc27a" ON "document" ("subject_type", "subject_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_60934b2ffc356b02d06cf16a80" ON "document" ("portfolio_id") `);
        await queryRunner.query(`ALTER TABLE "property" ADD CONSTRAINT "FK_95718674b77be6f75293e2365c8" FOREIGN KEY ("portfolio_id") REFERENCES "portfolio"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "portfolio" ADD CONSTRAINT "FK_ab77879067dc815468de31e63cf" FOREIGN KEY ("landlord_id") REFERENCES "user"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "notification" ADD CONSTRAINT "FK_5ec9aa64430984435e8a0262669" FOREIGN KEY ("portfolio_id") REFERENCES "portfolio"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "notification" ADD CONSTRAINT "FK_928b7aa1754e08e1ed7052cb9d8" FOREIGN KEY ("user_id") REFERENCES "user"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "portfolio_member" ADD CONSTRAINT "FK_c02eecc90e0de3c1742116fefa7" FOREIGN KEY ("portfolio_id") REFERENCES "portfolio"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "portfolio_member" ADD CONSTRAINT "FK_a2db3bb0a70771c7027c7309bff" FOREIGN KEY ("user_id") REFERENCES "user"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "unit" ADD CONSTRAINT "FK_de310cad4b93a905a01236c9ef2" FOREIGN KEY ("portfolio_id") REFERENCES "portfolio"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "unit" ADD CONSTRAINT "FK_ffd1df4d8c19a8bd49fcd8af71b" FOREIGN KEY ("property_id") REFERENCES "property"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "tenant" ADD CONSTRAINT "FK_3ce58fb50f708bf5666525d901a" FOREIGN KEY ("portfolio_id") REFERENCES "portfolio"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "lease" ADD CONSTRAINT "FK_007935258e588d12f311001000f" FOREIGN KEY ("portfolio_id") REFERENCES "portfolio"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "lease" ADD CONSTRAINT "FK_ca091675febe801029d4db0f642" FOREIGN KEY ("unit_id") REFERENCES "unit"("id") ON DELETE RESTRICT ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "lease_tenant" ADD CONSTRAINT "FK_1002d49fc6e6a01abf5308403c8" FOREIGN KEY ("lease_id") REFERENCES "lease"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "lease_tenant" ADD CONSTRAINT "FK_64b69371ab43b1453ba3e1229de" FOREIGN KEY ("tenant_id") REFERENCES "tenant"("id") ON DELETE RESTRICT ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "lease_charge" ADD CONSTRAINT "FK_5e94d7688d7fbee5a84b22fd375" FOREIGN KEY ("portfolio_id") REFERENCES "portfolio"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "lease_charge" ADD CONSTRAINT "FK_4ecd198da30e9be7ae2c8ffe9db" FOREIGN KEY ("lease_id") REFERENCES "lease"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "invoice_item" ADD CONSTRAINT "FK_9830c1881dd701d440c2164c3cd" FOREIGN KEY ("invoice_id") REFERENCES "invoice"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "invoice" ADD CONSTRAINT "FK_e423299afbc7c08bac6857a1777" FOREIGN KEY ("portfolio_id") REFERENCES "portfolio"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "invoice" ADD CONSTRAINT "FK_978738e43651936fd1b60c7e840" FOREIGN KEY ("lease_id") REFERENCES "lease"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "payment" ADD CONSTRAINT "FK_e03401e14c266f0f4e68954bf62" FOREIGN KEY ("portfolio_id") REFERENCES "portfolio"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "payment" ADD CONSTRAINT "FK_20cc84d8a2274ae86f551360c11" FOREIGN KEY ("invoice_id") REFERENCES "invoice"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "maintenance_request" ADD CONSTRAINT "FK_b36c96f0315a7ffd46d07e3a93e" FOREIGN KEY ("portfolio_id") REFERENCES "portfolio"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "maintenance_request" ADD CONSTRAINT "FK_7f5323bd769efb8011ca69035e7" FOREIGN KEY ("property_id") REFERENCES "property"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "maintenance_request" ADD CONSTRAINT "FK_7990604abb047d1e163e437fc6a" FOREIGN KEY ("unit_id") REFERENCES "unit"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "maintenance_request" ADD CONSTRAINT "FK_2bbd65a93cee313afc30fd7e407" FOREIGN KEY ("tenant_id") REFERENCES "tenant"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "work_order" ADD CONSTRAINT "FK_8e6b62c4caa787023767ae736b5" FOREIGN KEY ("portfolio_id") REFERENCES "portfolio"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "work_order" ADD CONSTRAINT "FK_8772bfa57c07975ab527b9e6740" FOREIGN KEY ("request_id") REFERENCES "maintenance_request"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "document" ADD CONSTRAINT "FK_60934b2ffc356b02d06cf16a80d" FOREIGN KEY ("portfolio_id") REFERENCES "portfolio"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
    }

    public async down(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE "document" DROP CONSTRAINT "FK_60934b2ffc356b02d06cf16a80d"`);
        await queryRunner.query(`ALTER TABLE "work_order" DROP CONSTRAINT "FK_8772bfa57c07975ab527b9e6740"`);
        await queryRunner.query(`ALTER TABLE "work_order" DROP CONSTRAINT "FK_8e6b62c4caa787023767ae736b5"`);
        await queryRunner.query(`ALTER TABLE "maintenance_request" DROP CONSTRAINT "FK_2bbd65a93cee313afc30fd7e407"`);
        await queryRunner.query(`ALTER TABLE "maintenance_request" DROP CONSTRAINT "FK_7990604abb047d1e163e437fc6a"`);
        await queryRunner.query(`ALTER TABLE "maintenance_request" DROP CONSTRAINT "FK_7f5323bd769efb8011ca69035e7"`);
        await queryRunner.query(`ALTER TABLE "maintenance_request" DROP CONSTRAINT "FK_b36c96f0315a7ffd46d07e3a93e"`);
        await queryRunner.query(`ALTER TABLE "payment" DROP CONSTRAINT "FK_20cc84d8a2274ae86f551360c11"`);
        await queryRunner.query(`ALTER TABLE "payment" DROP CONSTRAINT "FK_e03401e14c266f0f4e68954bf62"`);
        await queryRunner.query(`ALTER TABLE "invoice" DROP CONSTRAINT "FK_978738e43651936fd1b60c7e840"`);
        await queryRunner.query(`ALTER TABLE "invoice" DROP CONSTRAINT "FK_e423299afbc7c08bac6857a1777"`);
        await queryRunner.query(`ALTER TABLE "invoice_item" DROP CONSTRAINT "FK_9830c1881dd701d440c2164c3cd"`);
        await queryRunner.query(`ALTER TABLE "lease_charge" DROP CONSTRAINT "FK_4ecd198da30e9be7ae2c8ffe9db"`);
        await queryRunner.query(`ALTER TABLE "lease_charge" DROP CONSTRAINT "FK_5e94d7688d7fbee5a84b22fd375"`);
        await queryRunner.query(`ALTER TABLE "lease_tenant" DROP CONSTRAINT "FK_64b69371ab43b1453ba3e1229de"`);
        await queryRunner.query(`ALTER TABLE "lease_tenant" DROP CONSTRAINT "FK_1002d49fc6e6a01abf5308403c8"`);
        await queryRunner.query(`ALTER TABLE "lease" DROP CONSTRAINT "FK_ca091675febe801029d4db0f642"`);
        await queryRunner.query(`ALTER TABLE "lease" DROP CONSTRAINT "FK_007935258e588d12f311001000f"`);
        await queryRunner.query(`ALTER TABLE "tenant" DROP CONSTRAINT "FK_3ce58fb50f708bf5666525d901a"`);
        await queryRunner.query(`ALTER TABLE "unit" DROP CONSTRAINT "FK_ffd1df4d8c19a8bd49fcd8af71b"`);
        await queryRunner.query(`ALTER TABLE "unit" DROP CONSTRAINT "FK_de310cad4b93a905a01236c9ef2"`);
        await queryRunner.query(`ALTER TABLE "portfolio_member" DROP CONSTRAINT "FK_a2db3bb0a70771c7027c7309bff"`);
        await queryRunner.query(`ALTER TABLE "portfolio_member" DROP CONSTRAINT "FK_c02eecc90e0de3c1742116fefa7"`);
        await queryRunner.query(`ALTER TABLE "notification" DROP CONSTRAINT "FK_928b7aa1754e08e1ed7052cb9d8"`);
        await queryRunner.query(`ALTER TABLE "notification" DROP CONSTRAINT "FK_5ec9aa64430984435e8a0262669"`);
        await queryRunner.query(`ALTER TABLE "portfolio" DROP CONSTRAINT "FK_ab77879067dc815468de31e63cf"`);
        await queryRunner.query(`ALTER TABLE "property" DROP CONSTRAINT "FK_95718674b77be6f75293e2365c8"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_60934b2ffc356b02d06cf16a80"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_e56984b82e77d9ec67652cc27a"`);
        await queryRunner.query(`DROP TABLE "document"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_8e6b62c4caa787023767ae736b"`);
        await queryRunner.query(`DROP TABLE "work_order"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_b36c96f0315a7ffd46d07e3a93"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_c4eaf0a99dece1b96c9a30185b"`);
        await queryRunner.query(`DROP TABLE "maintenance_request"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_e03401e14c266f0f4e68954bf6"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_20cc84d8a2274ae86f551360c1"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_2c5c19ef08665dd1d123aebe50"`);
        await queryRunner.query(`DROP TABLE "payment"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_e423299afbc7c08bac6857a177"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_978738e43651936fd1b60c7e84"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_fc80c537671ddc29aab503e8fd"`);
        await queryRunner.query(`DROP TABLE "invoice"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_9830c1881dd701d440c2164c3c"`);
        await queryRunner.query(`DROP TABLE "invoice_item"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_5e94d7688d7fbee5a84b22fd37"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_4ecd198da30e9be7ae2c8ffe9d"`);
        await queryRunner.query(`DROP TABLE "lease_charge"`);
        await queryRunner.query(`DROP TABLE "lease_tenant"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_007935258e588d12f311001000"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_ca091675febe801029d4db0f64"`);
        await queryRunner.query(`DROP TABLE "lease"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_3ce58fb50f708bf5666525d901"`);
        await queryRunner.query(`DROP TABLE "tenant"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_de310cad4b93a905a01236c9ef"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_ffd1df4d8c19a8bd49fcd8af71"`);
        await queryRunner.query(`DROP TABLE "unit"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_c02eecc90e0de3c1742116fefa"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_a2db3bb0a70771c7027c7309bf"`);
        await queryRunner.query(`DROP TABLE "portfolio_member"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_e12875dfb3b1d92d7d7c5377e2"`);
        await queryRunner.query(`DROP TABLE "user"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_928b7aa1754e08e1ed7052cb9d"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_aedc307c7e60ecb138e3f90ff8"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_7d60478bf7cacbbe3f7ae1bc1c"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_5ec9aa64430984435e8a026266"`);
        await queryRunner.query(`DROP TABLE "notification"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_ab77879067dc815468de31e63c"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_93a62ca3d718772835184d0dda"`);
        await queryRunner.query(`DROP TABLE "portfolio"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_45cbf848b958b21e6c1547df95"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_85d8ae8f941ec5241e515bf69c"`);
        await queryRunner.query(`DROP TABLE "property"`);
    }

}
