import { MigrationInterface, QueryRunner } from "typeorm";

export class InitialSchema1759909592043 implements MigrationInterface {
    name = 'InitialSchema1759909592043'

    public async up(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`CREATE TABLE "units" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "deleted_at" TIMESTAMP WITH TIME ZONE, "is_deleted" boolean NOT NULL DEFAULT false, "property_id" uuid, "label" character varying NOT NULL, "bedrooms" integer, "bathrooms" integer, "sqft" integer, "market_rent" numeric(12,2), "status" character varying NOT NULL DEFAULT 'vacant', CONSTRAINT "UQ_bcc80efc2aa93aba83a7e3f6414" UNIQUE ("property_id", "label"), CONSTRAINT "PK_5a8f2f064919b587d93936cb223" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_f221e6d7bfd686266003b982b5" ON "units" ("property_id") `);
        await queryRunner.query(`CREATE TABLE "property" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "deleted_at" TIMESTAMP WITH TIME ZONE, "is_deleted" boolean NOT NULL DEFAULT false, "portfolio_id" uuid, "name" character varying NOT NULL, "address_line1" character varying, "address_line2" character varying, "city" character varying, "state" character varying, "postal_code" character varying, "country" character varying, "latitude" numeric(10,6), "longitude" numeric(10,6), "property_type" character varying NOT NULL, "description" text, CONSTRAINT "PK_d80743e6191258a5003d5843b4f" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_85d8ae8f941ec5241e515bf69c" ON "property" ("property_type") `);
        await queryRunner.query(`CREATE INDEX "IDX_45cbf848b958b21e6c1547df95" ON "property" ("city", "state") `);
        await queryRunner.query(`CREATE TABLE "portfolio" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "deleted_at" TIMESTAMP WITH TIME ZONE, "is_deleted" boolean NOT NULL DEFAULT false, "name" character varying NOT NULL, "address" character varying, "city" character varying, "state" character varying, "postal_code" character varying, "country" character varying, "phone" character varying, "email" character varying, "website" character varying, "tax_id" character varying, "registration_number" character varying, "vat_number" character varying, "currency" character varying NOT NULL DEFAULT 'USD', "landlord_id" uuid, "subscription_plan" character varying NOT NULL, "provider_customer_id" character varying NOT NULL DEFAULT '', "status" character varying NOT NULL DEFAULT 'active', "timezone" character varying NOT NULL DEFAULT 'UTC', "logo_url" character varying, "invoice_settings" jsonb, CONSTRAINT "PK_6936bb92ca4b7cda0ff28794e48" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_93a62ca3d718772835184d0dda" ON "portfolio" ("status") `);
        await queryRunner.query(`CREATE INDEX "IDX_ab77879067dc815468de31e63c" ON "portfolio" ("landlord_id") `);
        await queryRunner.query(`CREATE TABLE "notification" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "deleted_at" TIMESTAMP WITH TIME ZONE, "is_deleted" boolean NOT NULL DEFAULT false, "portfolio_id" uuid NOT NULL, "user_id" uuid, "type" character varying NOT NULL, "message" text NOT NULL, "subject_type" character varying, "subject_id" bigint, "is_read" boolean NOT NULL DEFAULT false, "channel" character varying NOT NULL, "sent_at" TIMESTAMP WITH TIME ZONE, CONSTRAINT "PK_705b6c7cdf9b2c2ff7ac7872cb7" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_5ec9aa64430984435e8a026266" ON "notification" ("portfolio_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_7d60478bf7cacbbe3f7ae1bc1c" ON "notification" ("sent_at") `);
        await queryRunner.query(`CREATE INDEX "IDX_aedc307c7e60ecb138e3f90ff8" ON "notification" ("is_read") `);
        await queryRunner.query(`CREATE INDEX "IDX_928b7aa1754e08e1ed7052cb9d" ON "notification" ("user_id") `);
        await queryRunner.query(`CREATE TABLE "users" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "deleted_at" TIMESTAMP WITH TIME ZONE, "is_deleted" boolean NOT NULL DEFAULT false, "name" character varying NOT NULL, "email" character varying NOT NULL, "phone" character varying, "password_hash" character varying NOT NULL, "role" character varying NOT NULL, "profile_image_url" character varying, "is_active" boolean NOT NULL DEFAULT true, "last_login_at" TIMESTAMP WITH TIME ZONE, "requires_onboarding" boolean NOT NULL DEFAULT true, "onboarding_completed_at" TIMESTAMP WITH TIME ZONE, "language" character varying(10) NOT NULL DEFAULT 'en', CONSTRAINT "UQ_97672ac88f789774dd47f7c8be3" UNIQUE ("email"), CONSTRAINT "PK_a3ffb1c0c8416b9fc6f907b7433" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_97672ac88f789774dd47f7c8be" ON "users" ("email") `);
        await queryRunner.query(`CREATE TABLE "portfolio_member" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "deleted_at" TIMESTAMP WITH TIME ZONE, "is_deleted" boolean NOT NULL DEFAULT false, "portfolio_id" uuid NOT NULL, "user_id" uuid NOT NULL, "role" character varying NOT NULL, CONSTRAINT "UQ_c3f978c50b74de4cd6587b36084" UNIQUE ("portfolio_id", "user_id"), CONSTRAINT "PK_0bc1504f157abeb106a54c517a2" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_a2db3bb0a70771c7027c7309bf" ON "portfolio_member" ("user_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_c02eecc90e0de3c1742116fefa" ON "portfolio_member" ("portfolio_id") `);
        await queryRunner.query(`CREATE TABLE "lease" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "deleted_at" TIMESTAMP WITH TIME ZONE, "is_deleted" boolean NOT NULL DEFAULT false, "unit_id" uuid NOT NULL, "start_date" date NOT NULL, "end_date" date NOT NULL, "rent" numeric(12,2) NOT NULL, "deposit" numeric(12,2) NOT NULL DEFAULT '0', "billing_day" integer, "grace_days" integer, "late_fee_flat" numeric(12,2), "late_fee_percent" numeric(5,2), "notes" text, "status" character varying NOT NULL DEFAULT 'draft', CONSTRAINT "PK_954811694773f24986695203663" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_f11320558c167027aa972c92bf" ON "lease" ("status") `);
        await queryRunner.query(`CREATE INDEX "IDX_ca091675febe801029d4db0f64" ON "lease" ("unit_id") `);
        await queryRunner.query(`CREATE TABLE "lease_tenants" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "deleted_at" TIMESTAMP WITH TIME ZONE, "is_deleted" boolean NOT NULL DEFAULT false, "lease_id" uuid NOT NULL, "tenant_id" uuid NOT NULL, "is_primary" boolean NOT NULL DEFAULT false, "relationship" character varying, "moved_in_date" date, "moved_out_date" date, "notes" text, CONSTRAINT "PK_b642a4fb7d4b26983050d7f614f" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_576b8fe558493080323475f1e5" ON "lease_tenants" ("tenant_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_d62b0945a8bb802fdb3cd83b7d" ON "lease_tenants" ("lease_id") `);
        await queryRunner.query(`CREATE TABLE "tenant" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "deleted_at" TIMESTAMP WITH TIME ZONE, "is_deleted" boolean NOT NULL DEFAULT false, "portfolio_id" uuid, "first_name" character varying NOT NULL, "last_name" character varying NOT NULL, "email" character varying, "phone" character varying, "is_active" boolean NOT NULL DEFAULT true, CONSTRAINT "PK_da8c6efd67bb301e810e56ac139" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_3ce58fb50f708bf5666525d901" ON "tenant" ("portfolio_id") `);
        await queryRunner.query(`CREATE TABLE "lease_charge" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "lease_id" uuid NOT NULL, "name" character varying NOT NULL, "unit_id" uuid NOT NULL, "property_id" uuid NOT NULL, "amount" numeric(12,2) NOT NULL, "cadence" character varying NOT NULL DEFAULT 'monthly', "start_date" date NOT NULL, "end_date" date, "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "deleted_at" TIMESTAMP WITH TIME ZONE, CONSTRAINT "PK_09772a7297c9b7a7e1300be76ba" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_05ec29a7dc2334ac370eb8719c" ON "lease_charge" ("property_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_cb383f9d3e410323aa5c7232cc" ON "lease_charge" ("unit_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_4ecd198da30e9be7ae2c8ffe9d" ON "lease_charge" ("lease_id") `);
        await queryRunner.query(`CREATE TYPE "public"."payments_payment_method_enum" AS ENUM('credit_card', 'debit_card', 'bank_transfer', 'ach_transfer', 'wire_transfer', 'check', 'money_order', 'cash', 'paypal', 'venmo', 'zelle', 'cash_app', 'cryptocurrency', 'other')`);
        await queryRunner.query(`CREATE TYPE "public"."payments_status_enum" AS ENUM('pending', 'succeeded', 'failed', 'refunded')`);
        await queryRunner.query(`CREATE TABLE "payments" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "deleted_at" TIMESTAMP WITH TIME ZONE, "is_deleted" boolean NOT NULL DEFAULT false, "lease_id" uuid NOT NULL, "amount" numeric(12,2) NOT NULL, "unapplied_amount" numeric(12,2) NOT NULL DEFAULT '0', "payment_method" "public"."payments_payment_method_enum" NOT NULL DEFAULT 'bank_transfer', "payment_date" TIMESTAMP WITH TIME ZONE NOT NULL, "status" "public"."payments_status_enum" NOT NULL DEFAULT 'pending', "reference" character varying, "notes" text, CONSTRAINT "PK_197ab7af18c93fbb0c9b28b4a59" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_72fae2ace901fdd43c82702c86" ON "payments" ("lease_id") `);
        await queryRunner.query(`CREATE TABLE "payment_application" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "payment_id" uuid NOT NULL, "invoice_id" uuid NOT NULL, "amount" numeric(12,2) NOT NULL, "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), CONSTRAINT "PK_c5ef59ca781f304514e37deddb7" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_c5ef59ca781f304514e37deddb" ON "payment_application" ("id") `);
        await queryRunner.query(`CREATE INDEX "IDX_2b4fa2d71c82de59053aa0aca7" ON "payment_application" ("payment_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_9c8c30c178ebe905e59077f84a" ON "payment_application" ("invoice_id") `);
        await queryRunner.query(`CREATE TABLE "invoices" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "lease_id" uuid, "invoice_number" character varying(50) NOT NULL, "issue_date" date NOT NULL DEFAULT ('now'::text)::date, "due_date" date, "grace_days" integer NOT NULL DEFAULT '0', "subtotal" numeric(12,2) NOT NULL DEFAULT '0', "tax_rate" numeric(5,2) NOT NULL DEFAULT '0', "tax_amount" numeric(12,2) NOT NULL DEFAULT '0', "total_amount" numeric(12,2) NOT NULL DEFAULT '0', "amount_paid" numeric(12,2) NOT NULL DEFAULT '0', "balance_due" numeric(12,2) NOT NULL DEFAULT '0', "billing_month" character varying(7) NOT NULL, "period_start" date NOT NULL, "period_end" date NOT NULL, "status" character varying(20) NOT NULL DEFAULT 'draft', "notes" text, "terms" text, "sent_at" TIMESTAMP WITH TIME ZONE, "paid_at" TIMESTAMP WITH TIME ZONE, "voided_at" TIMESTAMP WITH TIME ZONE, "metadata" jsonb, "is_issued" boolean NOT NULL DEFAULT false, "items" jsonb NOT NULL DEFAULT '[]'::jsonb, "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "deleted_at" TIMESTAMP WITH TIME ZONE, CONSTRAINT "UQ_d8f8d3788694e1b3f96c42c36fb" UNIQUE ("invoice_number"), CONSTRAINT "PK_668cef7c22a427fd822cc1be3ce" PRIMARY KEY ("id")); COMMENT ON COLUMN "invoices"."invoice_number" IS 'Unique invoice number'; COMMENT ON COLUMN "invoices"."issue_date" IS 'Date when the invoice was created/issued'; COMMENT ON COLUMN "invoices"."due_date" IS 'Due date for payment'; COMMENT ON COLUMN "invoices"."grace_days" IS 'Grace period in days after due date before late fees apply'; COMMENT ON COLUMN "invoices"."subtotal" IS 'Subtotal amount before tax'; COMMENT ON COLUMN "invoices"."tax_rate" IS 'Tax rate in percentage'; COMMENT ON COLUMN "invoices"."tax_amount" IS 'Total tax amount'; COMMENT ON COLUMN "invoices"."total_amount" IS 'Total amount including tax'; COMMENT ON COLUMN "invoices"."amount_paid" IS 'Amount paid so far'; COMMENT ON COLUMN "invoices"."balance_due" IS 'Remaining balance'; COMMENT ON COLUMN "invoices"."billing_month" IS 'Billing month in YYYY-MM format'; COMMENT ON COLUMN "invoices"."period_start" IS 'Start date of the billing period'; COMMENT ON COLUMN "invoices"."period_end" IS 'End date of the billing period'; COMMENT ON COLUMN "invoices"."status" IS 'Current status of the invoice'; COMMENT ON COLUMN "invoices"."notes" IS 'Additional notes for the invoice'; COMMENT ON COLUMN "invoices"."terms" IS 'Terms and conditions for the invoice'; COMMENT ON COLUMN "invoices"."is_issued" IS 'Whether the invoice has been issued to the tenant'`);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_5721da3283cc742b1db3427e08" ON "invoices" ("lease_id", "billing_month") WHERE status != 'void'`);
        await queryRunner.query(`CREATE INDEX "IDX_298cb55cdf1a44fbcb097fdf69" ON "invoices" ("status", "due_date") `);
        await queryRunner.query(`CREATE INDEX "IDX_0457ee681a50419881ea2ee796" ON "invoices" ("due_date") `);
        await queryRunner.query(`CREATE INDEX "IDX_da309569f957adb1f09c8bb109" ON "invoices" ("lease_id") `);
        await queryRunner.query(`CREATE TABLE "maintenance_request" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "deleted_at" TIMESTAMP WITH TIME ZONE, "is_deleted" boolean NOT NULL DEFAULT false, "property_id" uuid NOT NULL, "unit_id" uuid, "tenant_id" uuid, "title" character varying NOT NULL, "description" text, "priority" character varying NOT NULL DEFAULT 'medium', "status" character varying NOT NULL DEFAULT 'open', CONSTRAINT "PK_d12252413b60c63b57fc4c0d0c9" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_c4eaf0a99dece1b96c9a30185b" ON "maintenance_request" ("status") `);
        await queryRunner.query(`CREATE TABLE "work_order" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "request_id" uuid NOT NULL, "vendor_id" character varying, "scheduled_for" TIMESTAMP WITH TIME ZONE, "cost_estimate" numeric(12,2), "cost_actual" numeric(12,2), "status" character varying NOT NULL DEFAULT 'scheduled', "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "deleted_at" TIMESTAMP WITH TIME ZONE, CONSTRAINT "PK_0730e63dd523d397530859cb6d1" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "document" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "deleted_at" TIMESTAMP WITH TIME ZONE, "is_deleted" boolean NOT NULL DEFAULT false, "subject_type" character varying NOT NULL, "subject_id" bigint NOT NULL, "filename" character varying NOT NULL, "storage_key" character varying NOT NULL, "mime_type" character varying, "size" integer, "metadata" jsonb, CONSTRAINT "PK_e57d3357f83f3cdc0acffc3d777" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_e56984b82e77d9ec67652cc27a" ON "document" ("subject_type", "subject_id") `);
        await queryRunner.query(`CREATE TYPE "public"."expenses_category_enum" AS ENUM('repairs', 'utilities', 'tax', 'insurance', 'maintenance', 'other')`);
        await queryRunner.query(`CREATE TYPE "public"."expenses_status_enum" AS ENUM('paid', 'pending', 'overdue')`);
        await queryRunner.query(`CREATE TYPE "public"."expenses_payment_method_enum" AS ENUM('credit_card', 'debit_card', 'bank_transfer', 'ach_transfer', 'wire_transfer', 'check', 'money_order', 'cash', 'paypal', 'venmo', 'zelle', 'cash_app', 'cryptocurrency', 'other')`);
        await queryRunner.query(`CREATE TABLE "expenses" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "deleted_at" TIMESTAMP WITH TIME ZONE, "is_deleted" boolean NOT NULL DEFAULT false, "property_id" uuid NOT NULL, "amount" numeric(12,2) NOT NULL, "category" "public"."expenses_category_enum" NOT NULL DEFAULT 'other', "date_incurred" date NOT NULL, "date_recorded" date NOT NULL DEFAULT ('now'::text)::date, "status" "public"."expenses_status_enum" NOT NULL DEFAULT 'pending', "description" text, "vendor" character varying, "payment_method" "public"."expenses_payment_method_enum", "receipt_url" character varying, "tax_amount" numeric(12,2) NOT NULL DEFAULT '0', CONSTRAINT "PK_94c3ceb17e3140abc9282c20610" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_e069bf5f4d4aaab62a84f24ca4" ON "expenses" ("category") `);
        await queryRunner.query(`CREATE INDEX "IDX_50cdbda94b90052d9543be08b8" ON "expenses" ("date_incurred") `);
        await queryRunner.query(`CREATE INDEX "IDX_d45651fdfe08150a636a034319" ON "expenses" ("property_id") `);
        await queryRunner.query(`ALTER TABLE "units" ADD CONSTRAINT "FK_f221e6d7bfd686266003b982b5f" FOREIGN KEY ("property_id") REFERENCES "property"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "property" ADD CONSTRAINT "FK_95718674b77be6f75293e2365c8" FOREIGN KEY ("portfolio_id") REFERENCES "portfolio"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "portfolio" ADD CONSTRAINT "FK_ab77879067dc815468de31e63cf" FOREIGN KEY ("landlord_id") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "notification" ADD CONSTRAINT "FK_5ec9aa64430984435e8a0262669" FOREIGN KEY ("portfolio_id") REFERENCES "portfolio"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "notification" ADD CONSTRAINT "FK_928b7aa1754e08e1ed7052cb9d8" FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "portfolio_member" ADD CONSTRAINT "FK_c02eecc90e0de3c1742116fefa7" FOREIGN KEY ("portfolio_id") REFERENCES "portfolio"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "portfolio_member" ADD CONSTRAINT "FK_a2db3bb0a70771c7027c7309bff" FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "lease" ADD CONSTRAINT "FK_ca091675febe801029d4db0f642" FOREIGN KEY ("unit_id") REFERENCES "units"("id") ON DELETE RESTRICT ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "lease_tenants" ADD CONSTRAINT "FK_d62b0945a8bb802fdb3cd83b7db" FOREIGN KEY ("lease_id") REFERENCES "lease"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "lease_tenants" ADD CONSTRAINT "FK_576b8fe558493080323475f1e54" FOREIGN KEY ("tenant_id") REFERENCES "tenant"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "tenant" ADD CONSTRAINT "FK_3ce58fb50f708bf5666525d901a" FOREIGN KEY ("portfolio_id") REFERENCES "portfolio"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "lease_charge" ADD CONSTRAINT "FK_4ecd198da30e9be7ae2c8ffe9db" FOREIGN KEY ("lease_id") REFERENCES "lease"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "lease_charge" ADD CONSTRAINT "FK_cb383f9d3e410323aa5c7232cc7" FOREIGN KEY ("unit_id") REFERENCES "units"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "lease_charge" ADD CONSTRAINT "FK_05ec29a7dc2334ac370eb8719c0" FOREIGN KEY ("property_id") REFERENCES "property"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "payments" ADD CONSTRAINT "FK_72fae2ace901fdd43c82702c860" FOREIGN KEY ("lease_id") REFERENCES "lease"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "payment_application" ADD CONSTRAINT "FK_2b4fa2d71c82de59053aa0aca72" FOREIGN KEY ("payment_id") REFERENCES "payments"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "payment_application" ADD CONSTRAINT "FK_9c8c30c178ebe905e59077f84ab" FOREIGN KEY ("invoice_id") REFERENCES "invoices"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "invoices" ADD CONSTRAINT "FK_da309569f957adb1f09c8bb1095" FOREIGN KEY ("lease_id") REFERENCES "lease"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "maintenance_request" ADD CONSTRAINT "FK_7f5323bd769efb8011ca69035e7" FOREIGN KEY ("property_id") REFERENCES "property"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "maintenance_request" ADD CONSTRAINT "FK_7990604abb047d1e163e437fc6a" FOREIGN KEY ("unit_id") REFERENCES "units"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "maintenance_request" ADD CONSTRAINT "FK_2bbd65a93cee313afc30fd7e407" FOREIGN KEY ("tenant_id") REFERENCES "tenant"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "work_order" ADD CONSTRAINT "FK_8772bfa57c07975ab527b9e6740" FOREIGN KEY ("request_id") REFERENCES "maintenance_request"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "expenses" ADD CONSTRAINT "FK_d45651fdfe08150a636a0343192" FOREIGN KEY ("property_id") REFERENCES "property"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
    }

    public async down(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE "expenses" DROP CONSTRAINT "FK_d45651fdfe08150a636a0343192"`);
        await queryRunner.query(`ALTER TABLE "work_order" DROP CONSTRAINT "FK_8772bfa57c07975ab527b9e6740"`);
        await queryRunner.query(`ALTER TABLE "maintenance_request" DROP CONSTRAINT "FK_2bbd65a93cee313afc30fd7e407"`);
        await queryRunner.query(`ALTER TABLE "maintenance_request" DROP CONSTRAINT "FK_7990604abb047d1e163e437fc6a"`);
        await queryRunner.query(`ALTER TABLE "maintenance_request" DROP CONSTRAINT "FK_7f5323bd769efb8011ca69035e7"`);
        await queryRunner.query(`ALTER TABLE "invoices" DROP CONSTRAINT "FK_da309569f957adb1f09c8bb1095"`);
        await queryRunner.query(`ALTER TABLE "payment_application" DROP CONSTRAINT "FK_9c8c30c178ebe905e59077f84ab"`);
        await queryRunner.query(`ALTER TABLE "payment_application" DROP CONSTRAINT "FK_2b4fa2d71c82de59053aa0aca72"`);
        await queryRunner.query(`ALTER TABLE "payments" DROP CONSTRAINT "FK_72fae2ace901fdd43c82702c860"`);
        await queryRunner.query(`ALTER TABLE "lease_charge" DROP CONSTRAINT "FK_05ec29a7dc2334ac370eb8719c0"`);
        await queryRunner.query(`ALTER TABLE "lease_charge" DROP CONSTRAINT "FK_cb383f9d3e410323aa5c7232cc7"`);
        await queryRunner.query(`ALTER TABLE "lease_charge" DROP CONSTRAINT "FK_4ecd198da30e9be7ae2c8ffe9db"`);
        await queryRunner.query(`ALTER TABLE "tenant" DROP CONSTRAINT "FK_3ce58fb50f708bf5666525d901a"`);
        await queryRunner.query(`ALTER TABLE "lease_tenants" DROP CONSTRAINT "FK_576b8fe558493080323475f1e54"`);
        await queryRunner.query(`ALTER TABLE "lease_tenants" DROP CONSTRAINT "FK_d62b0945a8bb802fdb3cd83b7db"`);
        await queryRunner.query(`ALTER TABLE "lease" DROP CONSTRAINT "FK_ca091675febe801029d4db0f642"`);
        await queryRunner.query(`ALTER TABLE "portfolio_member" DROP CONSTRAINT "FK_a2db3bb0a70771c7027c7309bff"`);
        await queryRunner.query(`ALTER TABLE "portfolio_member" DROP CONSTRAINT "FK_c02eecc90e0de3c1742116fefa7"`);
        await queryRunner.query(`ALTER TABLE "notification" DROP CONSTRAINT "FK_928b7aa1754e08e1ed7052cb9d8"`);
        await queryRunner.query(`ALTER TABLE "notification" DROP CONSTRAINT "FK_5ec9aa64430984435e8a0262669"`);
        await queryRunner.query(`ALTER TABLE "portfolio" DROP CONSTRAINT "FK_ab77879067dc815468de31e63cf"`);
        await queryRunner.query(`ALTER TABLE "property" DROP CONSTRAINT "FK_95718674b77be6f75293e2365c8"`);
        await queryRunner.query(`ALTER TABLE "units" DROP CONSTRAINT "FK_f221e6d7bfd686266003b982b5f"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_d45651fdfe08150a636a034319"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_50cdbda94b90052d9543be08b8"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_e069bf5f4d4aaab62a84f24ca4"`);
        await queryRunner.query(`DROP TABLE "expenses"`);
        await queryRunner.query(`DROP TYPE "public"."expenses_payment_method_enum"`);
        await queryRunner.query(`DROP TYPE "public"."expenses_status_enum"`);
        await queryRunner.query(`DROP TYPE "public"."expenses_category_enum"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_e56984b82e77d9ec67652cc27a"`);
        await queryRunner.query(`DROP TABLE "document"`);
        await queryRunner.query(`DROP TABLE "work_order"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_c4eaf0a99dece1b96c9a30185b"`);
        await queryRunner.query(`DROP TABLE "maintenance_request"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_da309569f957adb1f09c8bb109"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_0457ee681a50419881ea2ee796"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_298cb55cdf1a44fbcb097fdf69"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_5721da3283cc742b1db3427e08"`);
        await queryRunner.query(`DROP TABLE "invoices"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_9c8c30c178ebe905e59077f84a"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_2b4fa2d71c82de59053aa0aca7"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_c5ef59ca781f304514e37deddb"`);
        await queryRunner.query(`DROP TABLE "payment_application"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_72fae2ace901fdd43c82702c86"`);
        await queryRunner.query(`DROP TABLE "payments"`);
        await queryRunner.query(`DROP TYPE "public"."payments_status_enum"`);
        await queryRunner.query(`DROP TYPE "public"."payments_payment_method_enum"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_4ecd198da30e9be7ae2c8ffe9d"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_cb383f9d3e410323aa5c7232cc"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_05ec29a7dc2334ac370eb8719c"`);
        await queryRunner.query(`DROP TABLE "lease_charge"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_3ce58fb50f708bf5666525d901"`);
        await queryRunner.query(`DROP TABLE "tenant"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_d62b0945a8bb802fdb3cd83b7d"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_576b8fe558493080323475f1e5"`);
        await queryRunner.query(`DROP TABLE "lease_tenants"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_ca091675febe801029d4db0f64"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_f11320558c167027aa972c92bf"`);
        await queryRunner.query(`DROP TABLE "lease"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_c02eecc90e0de3c1742116fefa"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_a2db3bb0a70771c7027c7309bf"`);
        await queryRunner.query(`DROP TABLE "portfolio_member"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_97672ac88f789774dd47f7c8be"`);
        await queryRunner.query(`DROP TABLE "users"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_928b7aa1754e08e1ed7052cb9d"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_aedc307c7e60ecb138e3f90ff8"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_7d60478bf7cacbbe3f7ae1bc1c"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_5ec9aa64430984435e8a026266"`);
        await queryRunner.query(`DROP TABLE "notification"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_ab77879067dc815468de31e63c"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_93a62ca3d718772835184d0dda"`);
        await queryRunner.query(`DROP TABLE "portfolio"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_45cbf848b958b21e6c1547df95"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_85d8ae8f941ec5241e515bf69c"`);
        await queryRunner.query(`DROP TABLE "property"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_f221e6d7bfd686266003b982b5"`);
        await queryRunner.query(`DROP TABLE "units"`);
    }

}
