version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    container_name: property_rental_management_postgres_dev
    environment:
      POSTGRES_DB: property_rental_management_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: rR%jrYKNqQdnYVQUkzuN
      POSTGRES_INITDB_ARGS: '--data-checksums'
      POSTGRES_HOST_AUTH_METHOD: trust
    command: >
      postgres 
      -c ssl=off 
      -c max_connections=100 
      -c ssl_cert_file=/etc/ssl/certs/ssl-cert-snakeoil.pem 
      -c ssl_key_file=/etc/ssl/private/ssl-cert-snakeoil.key
    ports:
      - "5432:5432"
    volumes:
      - postgres_dev_data:/var/lib/postgresql/data
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d property_rental_management_db"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - property_dev_network

  mailhog:
    image: mailhog/mailhog
    container_name: mailhog
    ports:
      - "1025:1025"
      - "8025:8025"
volumes:
  postgres_dev_data:

networks:
  property_dev_network:
    driver: bridge
