# render.yaml
services:
  - type: web
    name: property-management-api
    env: docker
    dockerfilePath: ./Dockerfile
    plan: free
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 8000
      - key: DB_SYNC
        value: false
      - key: DB_SSL
        value: true
      - key: ALLOWED_ORIGINS
        value: "https://property-manegment-frontend.vercel.app,http://localhost:3000"
      - key: COOKIE_KEY
        generateValue: true
      - key: ENABLE_SWAGGER
        value: true
      # JWT Configuration - REQUIRED
      - key: JWT_ACCESS_SECRET
        generateValue: true
      - key: JWT_ACCESS_EXPIRES_IN
        value: "15m"
      - key: JWT_REFRESH_SECRET
        generateValue: true
      - key: JWT_REFRESH_EXPIRES_IN
        value: "7d"
      # CSRF Configuration
      - key: CSRF_SECRET
        generateValue: true
      - key: CSRF_TOKEN_EXPIRY_HOURS
        value: "24"
      # Cookie Configuration (works with current vercel.app domain)
      - key: COOKIE_DOMAIN
        value: ".vercel.app"
      - key: COOKIE_SECURE
        value: true
      - key: COOKIE_SAME_SITE
        value: "none"
      - key: COOKIE_HTTP_ONLY
        value: true
      # Frontend/Backend domains (will update for custom domain later)
      - key: FRONTEND_DOMAIN
        value: "property-manegment-frontend.vercel.app"
      - key: BACKEND_DOMAIN
        value: "property-management-api.onrender.com"
      # Database Configuration
      - key: DB_HOST
        fromDatabase:
          name: property-management-db
          property: host
      - key: DB_PORT
        fromDatabase:
          name: property-management-db
          property: port
      - key: DB_USERNAME
        fromDatabase:
          name: property-management-db
          property: user
      - key: DB_PASSWORD
        fromDatabase:
          name: property-management-db
          property: password
      - key: DB_NAME
        fromDatabase:
          name: property-management-db
          property: database

databases:
  - name: property-management-db
    plan: free
    databaseName: property_management_prod
