services:
  - type: web
    name: property-management-api
    env: docker
    dockerfilePath: ./Dockerfile.prod
    plan: free
    autoDeploy: true
    buildCommand: |
      npm install -g pnpm@8.14.0
      pnpm install --frozen-lockfile
      pnpm run build
    startCommand: node dist/main.js
    healthCheckPath: /health
    instanceCount: 1
    env: node
    nodeVersion: 18.20.2
    envVars:
      # General Node / NestJS
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 3000
      - key: HOST
        value: 0.0.0.0
      - key: NPM_CONFIG_PRODUCTION
        value: 'false'
      # Database configuration
      - key: DATABASE_URL
        fromDatabase:
          name: property-management-db
          property: connectionString
      - key: DB_SYNC
        value: 'false'
      - key: RUN_MIGRATIONS_ON_BOOT
        value: 'true'
      - key: NODE_OPTIONS
        value: '--max_old_space_size=1024'
      - key: TZ
        value: 'UTC'

      # JWT Configuration
      - key: JWT_ACCESS_SECRET
        generateValue: true
      - key: JWT_ACCESS_EXPIRES_IN
        value: "15m"
      - key: JWT_REFRESH_SECRET
        generateValue: true
      - key: JWT_REFRESH_EXPIRES_IN
        value: "7d"

      # CSRF Configuration
      - key: CSRF_SECRET
        generateValue: true
      - key: CSRF_TOKEN_EXPIRY_HOURS
        value: "24"

      # Cookie Configuration
      - key: COOKIE_DOMAIN
        value: ""
      - key: COOKIE_SECURE
        value: true
      - key: COOKIE_SAME_SITE
        value: "none"
      - key: COOKIE_HTTP_ONLY
        value: true

      # Frontend/Backend Domains
      - key: FRONTEND_DOMAIN
        value: "property-manegment-frontend.vercel.app"
      - key: BACKEND_DOMAIN
        value: "property-management-api.onrender.com"

      # --- Neon Postgres Connection ---
      - key: DB_HOST
        value: ep-morning-math-ad0chyet-pooler.c-2.us-east-1.aws.neon.tech
      - key: DB_PORT
        value: "5432"
      - key: DB_USERNAME
        value: neondb_owner
      - key: DB_PASSWORD
        value: npg_L7XRIMNjGTo4
      - key: DB_NAME
        value: neondb
