services:
  - type: web
    name: property-management-api
    env: node
    buildCommand: npm install --include=dev && npm run build
    startCommand: npm run start:prod:migrate
    plan: free
    autoDeploy: true
    healthCheckPath: /health
    instanceCount: 1
