# render.yaml
services:
  # Main application service
  - type: web
    name: property-management-api
    env: docker
    dockerfilePath: ./Dockerfile
    plan: free
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 8000
      - key: DB_SYNC
        value: "false"
      - key: DB_SSL
        value: "true"
      - key: ALLOWED_ORIGINS
        value: "https://property-manegment-frontend.vercel.app,http://localhost:3000,https://property-management-api-7yk4.onrender.com"
      - key: COOKIE_KEY
        generateValue: true
      - key: ENABLE_SWAGGER
        value: "true"
      - key: RUN_MIGRATIONS_ON_BOOT
        value: "true"
      - key: JWT_ACCESS_SECRET
        generateValue: true
      - key: JWT_ACCESS_EXPIRES_IN
        value: "15m"
      - key: JWT_REFRESH_SECRET
        generateValue: true
      - key: JWT_REFRESH_EXPIRES_IN
        value: "7d"
      - key: CSRF_SECRET
        generateValue: true
      - key: CSRF_TOKEN_EXPIRY_HOURS
        value: "24"
      - key: COOKIE_DOMAIN
        value: ""
      - key: COOKIE_SECURE
        value: "true"
      - key: COOKIE_SAME_SITE
        value: "none"
      - key: COOKIE_HTTP_ONLY
        value: "true"
      - key: FRONTEND_DOMAIN
        value: "property-manegment-frontend.vercel.app"
      - key: DB_HOST
        fromDatabase:
          name: property-management-db
          property: host
      - key: DB_PORT
        fromDatabase:
          name: property-management-db
          property: port
      - key: DB_USERNAME
        fromDatabase:
          name: property-management-db
          property: user
      - key: DB_PASSWORD
        fromDatabase:
          name: property-management-db
          property: password
      - key: DB_NAME
        fromDatabase:
          name: property-management-db
          property: database

  # Database reset service
  - type: web
    name: db-reset
    env: docker
    dockerfilePath: ./Dockerfile.reset
    plan: free
    autoDeploy: false
    envVars:
      - key: NODE_ENV
        value: production
      - key: DB_HOST
        fromDatabase:
          name: property-management-db
          property: host
      - key: DB_PORT
        fromDatabase:
          name: property-management-db
          property: port
      - key: DB_USERNAME
        fromDatabase:
          name: property-management-db
          property: user
      - key: DB_PASSWORD
        fromDatabase:
          name: property-management-db
          property: password
      - key: DB_NAME
        fromDatabase:
          name: property-management-db
          property: database
      - key: DB_SSL
        value: "true"

databases:
  - name: property-management-db
    plan: free
    databaseName: property_management_prod